### ISSUE TITLE
relationshipMixin defineRelationProperty should check cachedRelations

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-connector-remote#12]
When calling remote `model.find` with include relationship, include relation is added to `__cachedRelations` to the returned model.

When calling `model.relation()` the remote connector should first check if the relationship model exists in cachedRelations and return the model instance.

Currently, the relationship is always pulled in from the remote server rendering the include filter useless.

**Comment by bajtos** [comment]
Good point. I believe this has to be fixed in loopback-datasource-juggler though.

**Comment by BerkeleyTrue** [comment]
Wouldn't it go here https://github.com/strongloop/loopback-connector-remote/blob/master/lib/relations.js#L197 ? This seems to be the first place the function call goes to, then it goes directly to calling the remoteMethodProxy.

**Comment by BerkeleyTrue** [comment]
Just stepping through the relation-definition in the juggler and I see what you mean.

**Comment by billinghamj** [comment]
What would the steps be to fixing this? Seems pretty critical.

**Comment by bajtos** [comment]
> What would the steps be to fixing this? Seems pretty critical.

@ritch I think you are more familiar with the remote connector than I am, can you advise please?

**Comment by glesage** [comment]
Is this the issue I'm seeing when I run this test: https://github.com/glesage/loopback-connector-remote/blob/fix-remote-relations/test/relations.test.js#L125 ?

I'm not familiar enough with the code to really know what's going on but I at least have a test to see exactly when it happens :P https://github.com/strongloop/loopback-connector-remote/pull/33

**Comment by doublemarked** [comment]
I see now that my comment/question in #42 is related to this. @bajtos @ritch - sticking a check `__cachedRelations` inside the relations.js would be simple enough, but is this really the core issue? Are we not losing other meaningful logic from the juggler? Are there problems with allowing the juggler to resolve relations (producing `find` calls, etc)? 

I'm also not very familiar with this code or the connector's design decisions - just started poking into it over the last day or two.
