### ISSUE TITLE
Aliases are not provided

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-connector-remote#14]
To reproduce:

`myModel.remove()` or `MyModel.destroyById()`

This should be a quick fix.

**Comment by ritch** [comment]
All we need to do is use the `remoteMethod.alias` array to setup the additional proxy methods:

https://github.com/strongloop/loopback-connector-remote/issues/14

**Comment by bajtos** [comment]
IMO this should be fixed before Offline Sync V1 release, I am assigning to @superkhau and moving to #tob.

**Comment by superkhau** [comment]
Connect to #18
