### ISSUE TITLE
Support custom http path of Model

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-remote#16]
LoopBack allows developers to customize Model http mapping, see https://github.com/strongloop/loopback/issues/698#issuecomment-68087181:

```js
// common/model/brand.json
{
  "name": "brand",
  "plural": "brands",
  "http": {
    "path": "domain1/brands"
  },
  // ...
}
```

AFAIK, the remoting connector ignores this setting and always uses the plural model name.

**Comment by bajtos** [comment]
The situation where a custom http path is useful: Local and Remote models used for replication. While it is true that one can use the `plural` option, I find such use rather hacky.

```js
// current solution
{
  "name": "RemoteTodo",
  "base": "Todo",
  "plural": "todos" // ???
}

// what I'd like to do instead
{
  "name": "RemoteTodo",
  "base": "Todo",
  "http": { "path": "/todos" }
}
```

On the other hand, `http.path` is specific to the REST transport and it will not work when using e.g. JSON-RPC or WebSockets.

Perhaps what we really need is a way for saying "this client Model" should invoke "that server Model".

@ritch thoughts?

**Comment by ritch** [comment]
> Perhaps what we really need is a way for saying "this client Model" should invoke "that server Model".

But then you need to resolve the path using the server model...
