### ISSUE TITLE
updateAttribute does not work

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback-connector-remote#19]
updateAttribute() does not work (tested on loopback-example-remote):

```
app.models.ReportModel.findById(1,
  function(err, reportModelInstance) {
    console.log('Find a ReportModel...');
    console.log(err || reportModelInstance);

    reportModelInstance.updateAttribute('content', rows, function(err, reportModelInstance) {
        console.log('Update a ReportModel...');
        console.log(err || reportModelInstance);
      });
  });
...
TypeError: Object #<Object> has no method 'updateAttribute'
```

But updateAll() does work (tested on loopback-example-remote):
```
app.models.ReportModel.findById(1,
  function(err, reportModelInstance) {
    console.log('Find a ReportModel...');
    console.log(err || reportModelInstance);

    reportModelInstance.content = rows;
    app.models.ReportModel.updateAll(
      {id: 1},
      reportModelInstance,
      function(err, reportModelInstance) {
        console.log('Update a ReportModel...');
        console.log(err || reportModelInstance);
      });
  });
```

Is this a bug or my mistake?

**Comment by joe-at-startupmedia** [comment]
I have the same issue.

**Comment by richardpringle** [comment]
Hey @pulkitsinghal and @joe-at-startupmedia, I have a quick fix for you! Use the [updateAttributes()](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattributes) method instead. All you have to do is pass in an object with a single property, for example: `{content: rows}`.

**Comment by richardpringle** [comment]
@ritchie and @raymondfeng, I'm not quite sure what causes the error but the `updateAttributes()` method is bound to the model prototype differently than the `updateAttribute()` method (no 's'). 
Regardless, it seems redundant to have both, is there a reason for this?

**Comment by richardpringle** [comment]
Not going to fix in LB2, but will fix in LB3. See #issue-no, closing.

**Comment by superkhau** [comment]
@richardpringle FYI, never remove triage labels.

**Comment by richardpringle** [comment]
^ my bad

**Comment by maektwain** [comment]
This is because you are trying to access Instance method, you cannot access updateAttribute like that.

model = new Model();
model.updateAttribute(values, values,cb).
