### ISSUE TITLE
Make connector-remote compatible with component-storage

### ISSUE THREAD

**Issue by richardpringle** [strongloop/loopback-connector-remote#25]
Right now, the component-storage methods aren't binding to a model with "remote" data-source. The remote connector should recognize that the data-source of the remote model is of type "component-storage" and bind the default methods.

**Comment by Fercho191** [comment]
Best regards, how is the status of this new feature? I am doing a project where I need to separate the storage server and application models, and want to do it with two Loopback projects, one with a storage component to connect to the remote connector

**Comment by richardpringle** [comment]
Hey @Fercho191, this feature is on hold right now since it does not have a lot of demand. You could definitely try implementing it if you would like!

Otherwise, I'm not sure that we will see any progress until we get more demand.

**Comment by Fercho191** [comment]
thanks for answering.
If this feature is not done, is there a way (without using remote connector) to separate the two projects?

**Comment by richardpringle** [comment]
@Fercho191 there are several ways to do so that really depend on your API design. I would make a model (`"base": "Model"`) that is not connected to a datasource (`"datasource": null`) with remote methods that make requests to the other API with the storage component. 

You can take a look at [storage-service.js](https://github.com/strongloop/loopback-component-storage/blob/310272c9301f7748307e8d28b3b9dc4d3250a8ce/lib/storage-service.js) if you want to see what metadata to provide the REST endpoints for the storage-service.
