### ISSUE TITLE
Add accessToken support

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-connector-remote#3]
Clients should set the `Authorization` header using the current user's `accessToken.id`. This will require a couple of new APIs in loopback and strong-remoting.

Related: https://github.com/strongloop/strong-remoting/issues/105 and https://github.com/strongloop/loopback-example-full-stack/issues/45

**Comment by bajtos** [comment]
> https://github.com/strongloop/strong-remoting/issues/105#issuecomment-88886695
>  I find this rather difficult to use, it took me quite a lot of debugging to find out where exactly the token should be set. I think we should add some sugar API to make this easier
```js
app.dataSources.remote.connector.remotes.auth = {
  bearer: new Buffer(token).toString('base64'),
  sendImmediately: true
};
```

**Comment by BerkeleyTrue** [comment]
:+1: for sugar

**Comment by bajtos** [comment]
Ideally, the connector should detect `login` and `logout` methods and update the access token automatically. Perhaps emit an event so that user code can install an event handler to persist the token in the local storage.

**Comment by lius** [comment]
The subject discussed here applies to the following scenario?

A user (using a client/browser) needs to access a model that do not exists in backend "local" database, which access another LB instance through remote connector to fetch the data.

Problem: the first backend (who receives browser requests) needs to access the remote one using the user access token, so the remote ACLs, validation and business logic could apply correctly. If I understand well, the access token used by remote connector is done at datasource level (e.g. in a boot script), but in this scenario it should be done dynamically, according to the access token sent by the browser for each concurrent request.

**Comment by bajtos** [comment]
> Problem: the first backend (who receives browser requests) needs to access the remote one using the user access token, so the remote ACLs, validation and business logic could apply correctly. If I understand well, the access token used by remote connector is done at datasource level (e.g. in a boot script), but in this scenario it should be done dynamically, according to the access token sent by the browser for each concurrent request.

So you have a proxy-like server that receives a client request from a browser and you want to forward it to another loopback backend, while preserving the identity (authentication) of the client that made the request. Like for example, to forward the `Authentication` header. Is my understanding correct?

The discussion above deals only with the client side (e.g. in the browser), so that `User.login` automatically updates the authentication settings for all subsequent requests made through the same datasource.

**Comment by lius** [comment]
@bajtos Ok, thanks. The scenario I mentioned is ok conceptually and should be moved to another issue on remote connector?

**Comment by bajtos** [comment]
> @lius The scenario I mentioned is ok conceptually and should be moved to another issue on remote connector?

Yes please.

**Comment by waldemarzahn** [comment]
hi @all
i have the same problem with some different loopback apis. I have implemented a small middleware to handle the auth token with different remote apis.

https://www.npmjs.com/package/loopback-rest-remote-auth-token

Tests are very welcome ;)
