### ISSUE TITLE
Npm install hangs on .sl-blip.js

### ISSUE THREAD

**Issue by googol** [strongloop/loopback-connector-remote#37]
Trying to install loopback in a vagrant managed virtualbox environment running ubuntu 14.04, node 4.2.6 and npm 3.7.1 the installation hangs at the preinstall script for loopback-connector-remote.

With npm 2.14.12 the installation finishes successfully.

Trying to install: loopback@2.26.2 -> loopback@2.26.2

**Comment by googol** [comment]
Other strongloop packages that have the sl-blip as an optional dependency have no problem installing.

I made a pull request to use the same style of sl-blip here: https://github.com/strongloop/loopback-connector-remote/pull/38

**Comment by richardpringle** [comment]
see #41 Instead

**Comment by richardpringle** [comment]
#41 merged, @googol  should work now. Closing
