### ISSUE TITLE
Support for promises?

### ISSUE THREAD

**Issue by jbcpollak** [strongloop/loopback-connector-remote#39]
I was accidentally using `loopback-connector-rest` for a remote loopback object. When I switched to `loopback-connector-remote` I was surprised that `find()`, `save()` and `upsert()` do not return promises. 

I didn't realize that was up to the connector. Are there any plans to add promise support to this project?

**Comment by richardpringle** [comment]
@jbcpollak, we should! Thanks for pointing this out.

**Comment by jbcpollak** [comment]
Thanks! 👍

**Comment by drywolf** [comment]
I just came a cross the same usecase, using Promises for the DAO methods in the browser.
Is there a scheduled release for the loopback-connector-remote on npm that will include this feature ?

I'm looking forward to it. :+1:

**Comment by richardpringle** [comment]
@drywolf, the package is up on npm.

Cheers

**Comment by drywolf** [comment]
Thanks :smiley:
