### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nVitius** [strongloop/loopback-connector-remote#45]
The existing documentation is really lacking. There's nothing regarding how to create a model so it can be used. I can gather most of it from the tests, but some info in the docs would be really helpful.

**Comment by richardpringle** [comment]
Hey @nVitius, what else would you like to see in the documentation? Did you see [the example](https://github.com/strongloop/loopback-example-connector/tree/remote)?

Simply put, the remote connector is just a way to use another LoopBack application as a datasource. If you can come up with some more specific questions about the connector, that might help us improve the documentation. Maybe we are assuming too much familiarity by the time you get to use this module. Let me know what you think and we will try to make some improvements!

**Comment by rblalock** [comment]
`Maybe we are assuming too much familiarity by the time you get to use this module.` <-- I think you nailed it there Richard.

**Comment by rblalock** [comment]
Tried to briefly address it here: https://github.com/strongloop/loopback-connector-remote/pull/51
