### ISSUE TITLE
what`s the difference between loopback-connector-remote and loopback-connector-rest? also and strong-remoting? 

### ISSUE THREAD

**Issue by a136464153** [strongloop/loopback-connector-remote#49]
what`s the difference between loopback-connector-remote and loopback-connector-rest? also and strong-remoting?

**Comment by a136464153** [comment]
I use strongloop@6.0.1 when I use slc loopback:datasource to create datasoucre with loopback-connector-remote. it shows me error. I select "other"  and type "remote" when it ask me for the connector name.

**Comment by a136464153** [comment]
![image](https://cloud.githubusercontent.com/assets/6264919/15819505/29ed7cb0-2c16-11e6-8f3c-14457598d0df.png)
I already use npm install loopback-connector-remote --save to install the remote feature on my example1.

**Comment by richardpringle** [comment]
Hey @a136464153, first of all, this is not the best place to ask questions, please post questions in one of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

`loopback-connector-remote` will only work with other loopback apps and you do not have to specify the remoting metadata. 
`loopback-connector-rest` is meant for 3rd party REST services.
`Strong-remoting` is the module that exposes the LoopBack REST API from the loopback app. `Strong-remoting` essentially takes the data from your `LoopBack` models and generates all the routes and metadata, etc. `Strong-remoting` is a dependency of `Loopback`.

As for issue with the cli, I believe we have fixed that. Try re-installing `strongloop` to get the latest version of [generator-loopback](https://github.com/strongloop/generator-loopback). If that doesn't work, please post a new issue on the [generator-loopback issues page](https://github.com/strongloop/generator-loopback/issues).
