### ISSUE TITLE
instance.save not promisified (vs Model.create which is)

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-connector-remote#65]
The following code does not return a promise:

```
const instance = new Model({key: 'val'})
return instance.save()
```

Whilst the following does:

```
return Model.create({key: 'val'})
```

This is different from other connectors in which all DAO methods return a promise if a callback is not supplied.

Calling `.save()` on a model instance should return a promise for a consistent DX.

**Comment by jbcpollak** [comment]
I've noticed if you are debugging and you step into `.save()` with a `remote` connector you go to `persisted-model.js`, but if you use `memory` or another connector you go into `dao.js`.

**Comment by jbcpollak** [comment]
I still think this is important and shouldn't be closed.

**Comment by lucamonfredo** [comment]
This should be reopened IMHO, it could lead to very subtle errors and documentation is not clear about that.
