### ISSUE TITLE
AssertionError: params must be an array

### ISSUE THREAD

**Issue by karthicktv** [strongloop/loopback-connector-remote#74]
Hi all,

I am using Loopback 3.0

I have two remote methods with single/multiple parameters and when I invoke the API, I get the following error; any ideas?

Thanks in advance!

{
  "error": {
    "statusCode": 500,
    "name": "AssertionError",
    "message": "params must be an array",
    "actual": false,
    "expected": true,
    "operator": "==",
    "generatedMessage": false,
    "stack": "AssertionError: params must be an array\n ..... "
  }
}

My remote method code set:

Lsagrmnt.getTestContract = function (agreementId, cb){
  var ds = Lsagrmnt.dataSource;
  var sql = "SELECT top 1 LS_AGRMNT_NR FROM LS_AGRMNT WHERE LS_AGRMNT_ID = ?";

  ds.connector.query(sql, agreementId, function (err, test)
  {
    if (err) console.error(err);
    cb(err, test);
  }
);
};

  Lsagrmnt.remoteMethod(
    'getTestContract', {
      http: {
        path: '/getTestContract',
        verb: 'get'
      },
      description : 'Test with one filter',
      accepts: { arg: 'agreementId', type: 'number'},
      returns: {
        arg: 'data',
        type: ['string'],
        root: true
      }
    }
  );

**Comment by xdien** [comment]
I think you missed square brackets here
`accepts: { arg: 'agreementId', type: 'number'},`
to
`accepts: { arg: 'agreementId', type: ['number']},`
