### ISSUE TITLE
Overriding a remoting type warning when a remote model has relations

### ISSUE THREAD

**Issue by angfal** [strongloop/loopback-connector-remote#81]
# Description/Steps to reproduce

When a remote model has relations, the model is registered an additional time per each relation. As the result, "Warning: overriding remoting type $MODEL_NAME".

It happens because the RemoteConnector.prototype.resolve() function is executed several times for the same model:

- in the RemoteConnector.prototype.define() function
- in each RelationMixin.$relation() function

# Link to reproduction sandbox

- https://github.com/angfal/remote-connector-warning
- git@github.com:angfal/remote-connector-warning.git

# Expected result

A remote model is registered only once.  No warnings in the log.

**Comment by bajtos** [comment]
Thank you for reporting this bug. I am afraid we don't have bandwidth to fix it ourselves, would you like to contribute the fix yourself? See http://loopback.io/doc/en/contrib/index.html to get you started.

**Comment by angfal** [comment]
I checked and it was fixed for me. Thanks
