### ISSUE TITLE
Multiple instances of strong-remoting causes assertion error on "sharedClass instanceof SharedClass"

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-connector-remote#9]
The connector directly depends on strong-remoting, which is a recipe for problems, as it causes multiple instances of the strong-remoting to be loaded in the Node process. See below for an example.

---

Using loopback-connector-remote 1.0.2, loopback 2.8.0.

Bundling loopback and serving to client. On initiation, my app crashes with `Uncaught AssertionError: false == true`, not a very helpful error message.

After some investigation, seems like this statement is the cause. Not sure what the solution would be since it seems like sharedClass object is an instance of SharedClass in this case but fails the test.

![sharedclassbug](https://cloud.githubusercontent.com/assets/6775919/5129560/4f41bffc-7098-11e4-944f-d809c041d0d9.gif)

**Comment by ritch** [comment]
I can confirm this is an issue as I just ran into it. I fixed it by running `npm dedup`... but that is because I was aware of what was going on. It would be quite confusing if you don't know you need to dedup your modules.

**Comment by BerkeleyTrue** [comment]
Just ran into it this in another project. Due to the nature of the project (we are using rxjs) the error stack trace was reporting it as an error within rxjs and not loopback. Would yall be open to a PR that makes the assert message descriptive, as `AssertionError: false == true` is extremely unhelpful. I was thinking something along the lines of 'sharedClass not instance of SharedClass, possible duplicate package error' .

**Comment by bajtos** [comment]
>  Would yall be open to a PR that makes the assert message descriptive, as AssertionError: false == true is extremely unhelpful. I was thinking something along the lines of 'sharedClass not instance of SharedClass, possible duplicate package error' .

:+1: :heavy_multiplication_x: :100:

**Comment by ritch** [comment]
https://github.com/strongloop/strong-remoting/pull/188

**Comment by BerkeleyTrue** [comment]
@ritch 's solution is much cleaner.

**Comment by bajtos** [comment]
We should still review all places where the remote connector is using strong-remoting and ensure we won't be bitten by the fact that there are multiple SharedClass around.

**Comment by ritch** [comment]
> We should still review all places where the remote connector is using strong-remoting and ensure we won't be bitten by the fact that there are multiple SharedClass around.

Can you create an issue for this if you think its important?
