### ISSUE TITLE
Unexpected return value when trying to receive relations

### ISSUE THREAD

**Issue by angfal** [strongloop/loopback-connector-remote#93]
# Description
There is a model instance with a remote connector (ex. `const instance = await MyModel.findById(...);`)

If to try to receive a relation via this model instance (`instance.relation();`) there are possible of two situations:

1. It returns a relation if it was included in the find query (it works great)
2. It returns a promise if nothing in cache (**here is problem**, as the other datasources return `undefined/null` in such cases)

# Expected result
The `instance.relation();` should return `undefined/null` instead of a `Promise` in case when no relation in `__cachedRelations`

**Comment by bajtos** [comment]
Thank you @angfal for reporting the issue. We don't have bandwidth to look into it, would you like to contribute the fix yourself?

**Comment by angfal** [comment]
@bajtos Why not, we fixed it for yourself. Will prepare PR during the week
